// examples/sveltekit/src/routes/debates/[id]/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { PageData } from './$types';

  export let data: PageData;
  $: debate = data.debate;

  let events: any[] = [];
  let connected = false;
  let ws: WebSocket | null = null;

  onMount(() => {
    if (debate.status === 'running') {
      const protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
      ws = new WebSocket(`${protocol}://${window.location.host}/ws/debate/${debate.debate_id}`);

      ws.onopen = () => (connected = true);
      ws.onclose = () => (connected = false);
      ws.onerror = () => (connected = false);
      ws.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data);
          events = [...events, { ...msg, timestamp: new Date().toISOString() }];
        } catch {
          // ignore non-JSON messages
        }
      };
    }
  });

  onDestroy(() => {
    if (ws) ws.close();
  });

  function formatConfidence(value: number): string {
    return (value * 100).toFixed(1) + '%';
  }
</script>

<div>
  <div style="margin-bottom: 2rem">
    <span
      class="status-badge"
      class:completed={debate.status === 'completed'}
      class:running={debate.status === 'running'}
    >
      {debate.status}
    </span>
    <h1 style="margin-top: 1rem">{debate.task}</h1>
    <p class="muted">
      Created {new Date(debate.created_at).toLocaleString()}
    </p>
  </div>

  <div class="grid">
    <div class="card">
      <h3>Agents</h3>
      <div class="agent-list">
        {#each debate.agents || [] as agent}
          <span class="agent-tag">{agent}</span>
        {/each}
      </div>
    </div>

    <div class="card">
      <h3>Progress</h3>
      <p>Round {debate.current_round || 0} of {debate.total_rounds || 9}</p>
      <div class="progress-bar">
        <div
          class="progress-fill"
          style="width: {((debate.current_round || 0) / (debate.total_rounds || 9)) * 100}%"
        />
      </div>
    </div>
  </div>

  {#if debate.status === 'running'}
    <div class="card" style="margin-top: 1rem">
      <h3>Live Stream</h3>
      <div class="connection-status">
        <div class="dot" class:connected />
        <span class="muted">{connected ? 'Connected' : 'Disconnected'}</span>
      </div>

      {#if events.length === 0}
        <p class="muted">Waiting for events...</p>
      {:else}
        {#each events as event, idx}
          <div class="stream-event">
            <div class="event-header">
              <strong>
                {event.type}
                {#if event.agent}({event.agent}){/if}
              </strong>
              <span class="timestamp">
                {new Date(event.timestamp).toLocaleTimeString()}
              </span>
            </div>
            {#if event.content}
              <p class="muted">
                {event.content.slice(0, 200)}{event.content.length > 200 ? '...' : ''}
              </p>
            {/if}
          </div>
        {/each}
      {/if}
    </div>
  {/if}

  {#if debate.status === 'completed' && debate.consensus}
    <div class="card consensus" style="margin-top: 1rem">
      <h3>Consensus Reached</h3>
      <p style="margin-bottom: 1rem">{debate.consensus.decision}</p>
      <div class="stats">
        <div>
          <span class="muted">Confidence</span>
          <p class="stat-value">{formatConfidence(debate.consensus.confidence)}</p>
        </div>
        <div>
          <span class="muted">Agreement</span>
          <p class="stat-value">
            {debate.consensus.votes_for}/{debate.consensus.votes_for + debate.consensus.votes_against}
          </p>
        </div>
      </div>
    </div>
  {/if}

  {#if debate.messages && debate.messages.length > 0}
    <div class="card" style="margin-top: 1rem">
      <h3>Debate History</h3>
      <div class="messages">
        {#each debate.messages as msg, idx}
          <div class="message">
            <div class="message-header">
              <strong>{msg.agent}</strong>
              <span class="muted">Round {msg.round} - {msg.phase}</span>
            </div>
            <p style="white-space: pre-wrap">{msg.content}</p>
          </div>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
  }

  .card {
    padding: 1.5rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
  }

  .consensus {
    border-color: #3b82f6;
    border-width: 2px;
  }

  .consensus h3 {
    color: #3b82f6;
  }

  .muted {
    opacity: 0.6;
  }

  .status-badge {
    padding: 0.25rem 0.75rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    background: #f3f4f6;
    color: #374151;
  }

  .status-badge.completed {
    background: #dcfce7;
    color: #166534;
  }

  .status-badge.running {
    background: #dbeafe;
    color: #1e40af;
  }

  .agent-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-top: 0.5rem;
  }

  .agent-tag {
    padding: 0.25rem 0.75rem;
    background: #f3f4f6;
    border-radius: 9999px;
    font-size: 0.875rem;
  }

  .progress-bar {
    margin-top: 0.5rem;
    background: #f3f4f6;
    border-radius: 9999px;
    height: 8px;
    overflow: hidden;
  }

  .progress-fill {
    height: 100%;
    background: #3b82f6;
    transition: width 0.3s;
  }

  .connection-status {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 1rem;
  }

  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: #ef4444;
  }

  .dot.connected {
    background: #22c55e;
  }

  .stream-event {
    padding: 0.75rem;
    border-bottom: 1px solid #e5e7eb;
  }

  .event-header {
    display: flex;
    justify-content: space-between;
    margin-bottom: 0.25rem;
  }

  .timestamp {
    font-size: 0.75rem;
    opacity: 0.6;
  }

  .stats {
    display: flex;
    gap: 2rem;
  }

  .stat-value {
    font-size: 1.25rem;
    font-weight: 600;
  }

  .messages {
    max-height: 500px;
    overflow-y: auto;
  }

  .message {
    padding: 1rem;
    border-bottom: 1px solid #e5e7eb;
  }

  .message-header {
    display: flex;
    justify-content: space-between;
    margin-bottom: 0.5rem;
  }
</style>

// examples/nextjs-app-router/app/debates/[id]/page.tsx
import { Suspense } from 'react';
import { getServerClient } from '@/lib/aragora';
import DebateStream from './DebateStream';

interface PageProps {
  params: { id: string };
}

// Fetch initial debate data on server
async function getDebate(id: string) {
  const client = getServerClient();
  try {
    return await client.debates.get(id);
  } catch (error) {
    console.error('Failed to fetch debate:', error);
    return null;
  }
}

export default async function DebateDetailPage({ params }: PageProps) {
  const debate = await getDebate(params.id);

  if (!debate) {
    return (
      <div className="card">
        <h2>Debate not found</h2>
        <p style={{ color: 'var(--text-muted)' }}>
          The debate with ID "{params.id}" could not be found.
        </p>
      </div>
    );
  }

  return (
    <div>
      <div style={{ marginBottom: '2rem' }}>
        <span className={`status-badge status-${debate.status}`}>
          {debate.status}
        </span>
        <h1 style={{ marginTop: '1rem' }}>{debate.task}</h1>
        <p style={{ color: 'var(--text-muted)' }}>
          Created {new Date(debate.created_at).toLocaleString()}
        </p>
      </div>

      <div className="grid" style={{ marginBottom: '2rem' }}>
        <div className="card">
          <h3>Agents</h3>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '0.5rem' }}>
            {(debate.agents || []).map((agent: string) => (
              <span
                key={agent}
                style={{
                  padding: '0.25rem 0.75rem',
                  background: 'var(--bg)',
                  borderRadius: '9999px',
                  fontSize: '0.875rem',
                }}
              >
                {agent}
              </span>
            ))}
          </div>
        </div>

        <div className="card">
          <h3>Progress</h3>
          <p style={{ marginTop: '0.5rem' }}>
            Round {debate.current_round || 0} of {debate.total_rounds || 9}
          </p>
          <div style={{ marginTop: '0.5rem', background: 'var(--bg)', borderRadius: '9999px', height: '8px', overflow: 'hidden' }}>
            <div
              style={{
                width: `${((debate.current_round || 0) / (debate.total_rounds || 9)) * 100}%`,
                height: '100%',
                background: 'var(--primary)',
                transition: 'width 0.3s',
              }}
            />
          </div>
        </div>
      </div>

      {/* Real-time stream for running debates */}
      {debate.status === 'running' && (
        <div className="card">
          <h3 style={{ marginBottom: '1rem' }}>Live Stream</h3>
          <Suspense fallback={<div>Connecting to stream...</div>}>
            <DebateStream debateId={params.id} />
          </Suspense>
        </div>
      )}

      {/* Consensus result for completed debates */}
      {debate.status === 'completed' && debate.consensus && (
        <div className="card" style={{ borderColor: 'var(--primary)' }}>
          <h3 style={{ color: 'var(--primary)', marginBottom: '1rem' }}>Consensus Reached</h3>
          <p style={{ marginBottom: '1rem' }}>{debate.consensus.decision}</p>
          <div style={{ display: 'flex', gap: '2rem' }}>
            <div>
              <span style={{ color: 'var(--text-muted)' }}>Confidence</span>
              <p style={{ fontSize: '1.25rem', fontWeight: 600 }}>
                {(debate.consensus.confidence * 100).toFixed(1)}%
              </p>
            </div>
            <div>
              <span style={{ color: 'var(--text-muted)' }}>Agreement</span>
              <p style={{ fontSize: '1.25rem', fontWeight: 600 }}>
                {debate.consensus.votes_for}/{debate.consensus.votes_for + debate.consensus.votes_against}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Messages history */}
      {debate.messages && debate.messages.length > 0 && (
        <div className="card">
          <h3 style={{ marginBottom: '1rem' }}>Debate History</h3>
          <div style={{ maxHeight: '500px', overflowY: 'auto' }}>
            {debate.messages.map((msg: any, idx: number) => (
              <div
                key={idx}
                style={{
                  padding: '1rem',
                  borderBottom: '1px solid var(--border)',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <strong>{msg.agent}</strong>
                  <span style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>
                    Round {msg.round} - {msg.phase}
                  </span>
                </div>
                <p style={{ whiteSpace: 'pre-wrap' }}>{msg.content}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
